//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:34:56 PM BRT 
//

package arcade.domain;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "dipvalue" })
@XmlRootElement(name = "dipswitch")
public class DipSwitch {

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "tag", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String tag;
	@XmlAttribute(name = "mask", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String mask;
	protected List<DipValue> dipvalue = new ArrayList<DipValue>();

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the tag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * Sets the value of the tag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTag(String value) {
		this.tag = value;
	}

	/**
	 * Gets the value of the mask property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMask() {
		return mask;
	}

	/**
	 * Sets the value of the mask property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMask(String value) {
		this.mask = value;
	}

	/**
	 * Gets the value of the dipvalue property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the dipvalue property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDipvalue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link DipValue }
	 * 
	 * 
	 */
	public List<DipValue> getDipvalue() {
		if (dipvalue == null) {
			dipvalue = new ArrayList<DipValue>();
		}
		return this.dipvalue;
	}

	public void addDipValue(DipValue dipValueTmp) {
		this.dipvalue.add(dipValueTmp);

	}

}
