//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:34:56 PM BRT 
//


package arcade.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "display")
public class Display {

    @XmlAttribute(name = "tag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tag;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "rotate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rotate;
    @XmlAttribute(name = "flipx")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String flipx;
    @XmlAttribute(name = "width")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String width;
    @XmlAttribute(name = "height")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String height;
    @XmlAttribute(name = "refresh", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String refresh;
    @XmlAttribute(name = "pixclock")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pixclock;
    @XmlAttribute(name = "htotal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String htotal;
    @XmlAttribute(name = "hbend")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hbend;
    @XmlAttribute(name = "hbstart")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hbstart;
    @XmlAttribute(name = "vtotal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vtotal;
    @XmlAttribute(name = "vbend")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vbend;
    @XmlAttribute(name = "vbstart")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vbstart;

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the rotate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotate() {
        return rotate;
    }

    /**
     * Sets the value of the rotate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotate(String value) {
        this.rotate = value;
    }

    /**
     * Gets the value of the flipx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlipx() {
        if (flipx == null) {
            return "no";
        } else {
            return flipx;
        }
    }

    /**
     * Sets the value of the flipx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlipx(String value) {
        this.flipx = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the refresh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefresh() {
        return refresh;
    }

    /**
     * Sets the value of the refresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefresh(String value) {
        this.refresh = value;
    }

    /**
     * Gets the value of the pixclock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPixclock() {
        return pixclock;
    }

    /**
     * Sets the value of the pixclock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPixclock(String value) {
        this.pixclock = value;
    }

    /**
     * Gets the value of the htotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtotal() {
        return htotal;
    }

    /**
     * Sets the value of the htotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtotal(String value) {
        this.htotal = value;
    }

    /**
     * Gets the value of the hbend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHbend() {
        return hbend;
    }

    /**
     * Sets the value of the hbend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHbend(String value) {
        this.hbend = value;
    }

    /**
     * Gets the value of the hbstart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHbstart() {
        return hbstart;
    }

    /**
     * Sets the value of the hbstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHbstart(String value) {
        this.hbstart = value;
    }

    /**
     * Gets the value of the vtotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVtotal() {
        return vtotal;
    }

    /**
     * Sets the value of the vtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVtotal(String value) {
        this.vtotal = value;
    }

    /**
     * Gets the value of the vbend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVbend() {
        return vbend;
    }

    /**
     * Sets the value of the vbend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVbend(String value) {
        this.vbend = value;
    }

    /**
     * Gets the value of the vbstart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVbstart() {
        return vbstart;
    }

    /**
     * Sets the value of the vbstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVbstart(String value) {
        this.vbstart = value;
    }

}
