//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:34:56 PM BRT 
//


package arcade.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "driver")
public class Driver {

    @XmlAttribute(name = "status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlAttribute(name = "emulation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String emulation;
    @XmlAttribute(name = "color", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String color;
    @XmlAttribute(name = "sound", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sound;
    @XmlAttribute(name = "graphic", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String graphic;
    @XmlAttribute(name = "cocktail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cocktail;
    @XmlAttribute(name = "protection")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String protection;
    @XmlAttribute(name = "savestate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String savestate;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the emulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmulation() {
        return emulation;
    }

    /**
     * Sets the value of the emulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmulation(String value) {
        this.emulation = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the sound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSound(String value) {
        this.sound = value;
    }

    /**
     * Gets the value of the graphic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphic() {
        return graphic;
    }

    /**
     * Sets the value of the graphic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphic(String value) {
        this.graphic = value;
    }

    /**
     * Gets the value of the cocktail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCocktail() {
        return cocktail;
    }

    /**
     * Sets the value of the cocktail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCocktail(String value) {
        this.cocktail = value;
    }

    /**
     * Gets the value of the protection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtection() {
        return protection;
    }

    /**
     * Sets the value of the protection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtection(String value) {
        this.protection = value;
    }

    /**
     * Gets the value of the savestate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSavestate() {
        return savestate;
    }

    /**
     * Sets the value of the savestate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSavestate(String value) {
        this.savestate = value;
    }

}
