//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:34:56 PM BRT 
//


package arcade.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "control"
})
@XmlRootElement(name = "input")
public class Input {

    @XmlAttribute(name = "service")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String service;
    @XmlAttribute(name = "tilt")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tilt;
    @XmlAttribute(name = "players", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String players;
    @XmlAttribute(name = "buttons")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String buttons;
    @XmlAttribute(name = "coins")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String coins;
    protected List<Control> control;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        if (service == null) {
            return "no";
        } else {
            return service;
        }
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the tilt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTilt() {
        if (tilt == null) {
            return "no";
        } else {
            return tilt;
        }
    }

    /**
     * Sets the value of the tilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTilt(String value) {
        this.tilt = value;
    }

    /**
     * Gets the value of the players property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayers() {
        return players;
    }

    /**
     * Sets the value of the players property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayers(String value) {
        this.players = value;
    }

    /**
     * Gets the value of the buttons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getButtons() {
        return buttons;
    }

    /**
     * Sets the value of the buttons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setButtons(String value) {
        this.buttons = value;
    }

    /**
     * Gets the value of the coins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoins() {
        return coins;
    }

    /**
     * Sets the value of the coins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoins(String value) {
        this.coins = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the control property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Control }
     * 
     * 
     */
    public List<Control> getControl() {
        if (control == null) {
            control = new ArrayList<Control>();
        }
        return this.control;
    }

}
