//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:34:56 PM BRT 
//


package arcade.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dustin.example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dustin.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link Analog }
     * 
     */
    public Analog createAnalog() {
        return new Analog();
    }

    /**
     * Create an instance of {@link DeviceRef }
     * 
     */
    public DeviceRef createDeviceRef() {
        return new DeviceRef();
    }

    /**
     * Create an instance of {@link Mame }
     * 
     */
    public Mame createMame() {
        return new Mame();
    }

    /**
     * Create an instance of {@link Machine }
     * 
     */
    public Machine createGame() {
        return new Machine();
    }

    /**
     * Create an instance of {@link Disk }
     * 
     */
    public Disk createDisk() {
        return new Disk();
    }

    /**
     * Create an instance of {@link DipSwitch }
     * 
     */
    public DipSwitch createDipswitch() {
        return new DipSwitch();
    }

    /**
     * Create an instance of {@link DipValue }
     * 
     */
    public DipValue createDipvalue() {
        return new DipValue();
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link BiosSet }
     * 
     */
    public BiosSet createBiosset() {
        return new BiosSet();
    }

    /**
     * Create an instance of {@link Slot }
     * 
     */
    public Slot createSlot() {
        return new Slot();
    }

    /**
     * Create an instance of {@link Slotoption }
     * 
     */
    public Slotoption createSlotoption() {
        return new Slotoption();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link Chip }
     * 
     */
    public Chip createChip() {
        return new Chip();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link Rom }
     * 
     */
    public Rom createRom() {
        return new Rom();
    }

    /**
     * Create an instance of {@link Confsetting }
     * 
     */
    public Confsetting createConfsetting() {
        return new Confsetting();
    }

    /**
     * Create an instance of {@link Display }
     * 
     */
    public Display createDisplay() {
        return new Display();
    }

    /**
     * Create an instance of {@link Sound }
     * 
     */
    public Sound createSound() {
        return new Sound();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Adjuster }
     * 
     */
    public Adjuster createAdjuster() {
        return new Adjuster();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Softwarelist }
     * 
     */
    public Softwarelist createSoftwarelist() {
        return new Softwarelist();
    }

    /**
     * Create an instance of {@link Ramoption }
     * 
     */
    public Ramoption createRamoption() {
        return new Ramoption();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

}
