//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.06 at 10:13:38 PM BRT 
//

package arcade.domain;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "feature", "dataarea", "diskarea", "dipswitch" })
@XmlRootElement(name = "part")
public class Part {

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "interface", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String _interface;
	protected List<Feature> feature;
	protected List<Dataarea> dataarea;
	protected List<Diskarea> diskarea;
	protected List<DipSwitch> dipswitch;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the interface property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInterface() {
		return _interface;
	}

	/**
	 * Sets the value of the interface property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setInterface(String value) {
		this._interface = value;
	}

	/**
	 * Gets the value of the feature property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the feature property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFeature().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Feature }
	 * 
	 * 
	 */
	public List<Feature> getFeature() {
		if (feature == null) {
			feature = new ArrayList<Feature>();
		}
		return this.feature;
	}

	/**
	 * Gets the value of the dataarea property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the dataarea property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDataarea().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Dataarea }
	 * 
	 * 
	 */
	public List<Dataarea> getDataarea() {
		if (dataarea == null) {
			dataarea = new ArrayList<Dataarea>();
		}
		return this.dataarea;
	}

	/**
	 * Gets the value of the diskarea property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the diskarea property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDiskarea().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Diskarea }
	 * 
	 * 
	 */
	public List<Diskarea> getDiskarea() {
		if (diskarea == null) {
			diskarea = new ArrayList<Diskarea>();
		}
		return this.diskarea;
	}

	/**
	 * Gets the value of the dipswitch property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the dipswitch property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDipswitch().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Dipswitch }
	 * 
	 * 
	 */
	public List<DipSwitch> getDipswitch() {
		if (dipswitch == null) {
			dipswitch = new ArrayList<DipSwitch>();
		}
		return this.dipswitch;
	}

}
