//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:34:56 PM BRT 
//

package arcade.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "rom")
public class Rom {

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String name;
	@XmlAttribute(name = "bios")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String bios;
	@XmlAttribute(name = "size", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String size;
	@XmlAttribute(name = "crc")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String crc;
	@XmlAttribute(name = "sha1")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String sha1;
	@XmlAttribute(name = "merge")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String merge;
	@XmlAttribute(name = "region")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String region;
	@XmlAttribute(name = "offset")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String offset;
	@XmlAttribute(name = "status")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String status;
	@XmlAttribute(name = "optional")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String optional;
	protected String md5;
	protected Machine software;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the bios property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBios() {
		return bios;
	}

	/**
	 * Sets the value of the bios property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBios(String value) {
		this.bios = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSize() {
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSize(String value) {
		this.size = value;
	}

	/**
	 * Gets the value of the crc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCrc() {
		return crc;
	}

	/**
	 * Sets the value of the crc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCrc(String value) {
		this.crc = value;
	}

	/**
	 * Gets the value of the sha1 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSha1() {
		return sha1;
	}

	/**
	 * Sets the value of the sha1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSha1(String value) {
		this.sha1 = value;
	}

	/**
	 * Gets the value of the merge property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMerge() {
		return merge;
	}

	/**
	 * Sets the value of the merge property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMerge(String value) {
		this.merge = value;
	}

	/**
	 * Gets the value of the region property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * Sets the value of the region property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRegion(String value) {
		this.region = value;
	}

	/**
	 * Gets the value of the offset property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOffset() {
		return offset;
	}

	/**
	 * Sets the value of the offset property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOffset(String value) {
		this.offset = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		if (status == null) {
			return "good";
		} else {
			return status;
		}
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the optional property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOptional() {
		if (optional == null) {
			return "no";
		} else {
			return optional;
		}
	}

	/**
	 * Sets the value of the optional property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOptional(String value) {
		this.optional = value;
	}

	public String getMd5() {
		return md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	/**
	 * @return the software
	 */
	public Machine getSoftware() {
		return software;
	}

	/**
	 * @param software
	 *            the software to set
	 */
	public void setSoftware(Machine software) {
		this.software = software;
	}

}
